#!/usr/bin/env bash
#Script that quires the DNS and retrieves information
#Based on the Domain and Sub Domains Passed as Args

domain=$1
subdomain=$2

display(){
    dig "$1" | awk '/;; ANSWER SECTION:/{ isfound=1 ; next }
	isfound == 1 {print "The subdomain " substr(split($1, a, ".")a[1], 2) " is a " $4 " record and points to " $5; exit}'
}

if [ "$#" -eq 1 ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for item in "${subdomains[@]}"; do
        display "$item.$domain"
    done
elif [ "$#" -eq 2 ]; then
    display "$subdomain.$domain"
fi
