#!/usr/bin/env bash
#Script to install nginx onto a server

sudo apt update -y
sudo apt install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart