#!/usr/bin/env bash
#Configuring Nginx to redirect to another page with custom 404-error
sudo apt update -y
sudo apt install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;

    error_page 404 /404_html;

    location /404.html {
        root /var/www/html/;
		internal;
	}

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" > /etc/nginx/sites-available/default
    
sudo service nginx restart