#!/usr/bin/env bash
#Configures a server to listen to port 80

echo "server {

    listen 80 default_server;
    listen [::]: 80 default_server ipv6only=on;

    root /var/www/html

    index index.html index.htm index.nginx-debian.html;
	server_name _;

    server_name localhost;

        location / {
                try_files \$uri \$uri/ =404;
        }
}" | sudo tee /etc/nginx/sites-enabled/default
sudo service nginx restart


