#!/usr/bin/env bash
# Bash script printing fizzbuzz
count=1
for ((; count <= 100; count++ ));
do
	if  (("$count" % 3 == 0 && "$count" % 5 == 0))
	then
		echo "FizzBuzz"
	elif  (("$count" % 3 == 0))
	then
		echo "Fizz"
	elif (("$count" % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$count"
	fi
done;
