#!/usr/bin/env bash
# script that displays Best School 10 times, using while loop

string="Best School"
count=0
num_to_print=10

while ((count < num_to_print));
do
	echo "$string"
	count=$((count + 1));
done
