#!/usr/bin/env bash
# script that displays Best School 10 times, using until
count=0
string="Best School"
num_of_print=10
until ((count >= num_of_print));
do
	echo "$string"
	count=$((count + 1));
done
