#!/usr/bin/env bash
#Printing using a while loop with a if conditional
count=0
string="Best School"
num_of_prints=10
while (( count < num_of_prints ));
do
	echo "$string"

	if [ $count = 8 ]
	then
		echo "Hi"
	fi

	count=$((count + 1));
done
