#!/usr/bin/env bash
#script that displays the time for 12 hours and 59 minutes
hours=0
mins=1
while (( hours < 12 ));
do
	echo "Hour : $hours"
	mins=1
	while (( mins < 60 ));
	do
		echo "$mins"
		mins=$(( mins + 1 ));
	done;
	hours=$(( hours + 1 ));
done
